### ISSUE TITLE
docs(zh-cn): translation review epic issue

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/test-utils#2561]
This is an epic issue calling for docs review for the Simplified Chinese docs translation (zh-cn) https://github.com/vuejs/test-utils/pull/2552.

to all Vue Test Utils maintainers: sorry about the potential upcoming noisy notifications in Chinese 🙏 

该 issue 用于发起并追踪 Vue Test Utils 中文文档翻译的校对工作，大家可以在此留言认领要校对的文档。

----

**大家如果想参与校对，流程如下：**

1. 直接在此留言注明自己认领哪一篇，然后
2. fork 该仓库、review、提交您的改动意见
3. 发 PR，在 PR 里注明自己 review 的是哪一篇

注意事项：

- 原则上以 md 文件为单位。我们建议 review 一篇结束之后再认领下一篇，避免自己长时间无法交付的情况下阻塞其他人的参与。但我们不介意更大颗粒度的认领，以避免不必要的更多的消息打扰，请量力而为。
- 遵循 Vue 社区的[中文翻译约定](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)，同时推荐一个格式化小工具 [zhlint](https://www.npmjs.com/package/zhlint)，可在校对过程中配合使用
- 原则上先到先得，但如果您对已经 review 过的内容仍不满意，我们也欢迎另行开 issue 或 PR 讨论，我们不在此 epic issue 做汇总或特别追踪。
- 译法讨论我们也欢迎到 Vue 官网的中文翻译 repo 开 [issue](https://github.com/vuejs-translations/docs-zh-cn/issues?q=is%3Aissue+is%3Aopen+label%3A%E7%BF%BB%E8%AF%91%E8%AE%A8%E8%AE%BA) 讨论

认领和完成情况追踪 (会保持更新)：

- [x] `├── api`
- [x] `│   └── index.md` @h7ml 
- [x] `├── guide`
- [x] `│   ├── advanced`
- [x] `│   │   ├── async-suspense.md` @lxKylin 
- [x] `│   │   ├── component-instance.md` @Jinjiang 
- [x] `│   │   ├── http-requests.md` @lxKylin 
- [x] `│   │   ├── reusability-composition.md` @Jinjiang 
- [x] `│   │   ├── slots.md` @qq466610987 
- [x] `│   │   ├── ssr.md` @Jinjiang 
- [x] `│   │   ├── stubs-shallow-mount.md` @Jinjiang 
- [x] `│   │   ├── teleport.md` @Jinjiang 
- [x] `│   │   ├── transitions.md` @Jinjiang 
- [x] `│   │   ├── v-model.md` @Jinjiang
- [x] `│   │   ├── vue-router.md` @Jinjiang
- [x] `│   │   └── vuex.md` @Jinjiang
- [x] `│   ├── essentials`
- [x] `│   │   ├── a-crash-course.md` @Jinjiang 
- [x] `│   │   ├── conditional-rendering.md` @chenqianhe
- [x] `│   │   ├── easy-to-test.md` @KiritaniAyaka 
- [x] `│   │   ├── event-handling.md` @lxKylin 
- [x] `│   │   ├── forms.md` @Jinjiang 
- [x] `│   │   └── passing-data.md` @lxKylin 
- [x] `│   ├── extending-vtu`
- [x] `│   │   ├── community-learning.md` @Jinjiang
- [x] `│   │   └── plugins.md` @Jinjiang
- [x] `│   ├── faq`
- [x] `│   │   └── index.md` @h7ml 
- [x] `│   └── index.md` @Jinjiang
- [x] `├── index.md` @Jinjiang
- [x] `├── installation` @Jinjiang
- [x] `│   └── index.md` @Jinjiang
- [x] `└── migration`
- [x] `    └── index.md` @Jinjiang
- [x] 术语统一：stub - 测试替身 https://github.com/vuejs-translations/docs-zh-cn/issues/1057

谢谢

**Comment by Jinjiang** [comment]
我自己先认领 `guide/essentials/a-crash-course.md` 算是做个示范

**Comment by KiritaniAyaka** [comment]
认领 `guide/essentials/easy-to-test.md`

**Comment by qq466610987** [comment]
认领 `guide/advanced/slots.md`

**Comment by h7ml** [comment]
认领 /api/index.md

**Comment by lxKylin** [comment]
认领guide/essentials/event-handling.md

**Comment by lxKylin** [comment]
认领guide/essentials/passing-data.md

**Comment by lxKylin** [comment]
认领guide/advanced/async-suspense.md

**Comment by h7ml** [comment]
认领/guide/faq/index.md

**Comment by lxKylin** [comment]
认领guide/advanced/http-requests.md

**Comment by vaesonshu** [comment]
认领 guide/advanced/vuex.md

**Comment by Jinjiang** [comment]
目前所有的翻译均已经过至少一轮 review，该 issue 将关闭。感谢各位的参与和贡献！
