### ISSUE TITLE
Alpha-0 API

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/test-utils#26]
I propose the following API for alpha-0. Progress is tracked here: https://github.com/vuejs/vue-test-utils-next/projects/1

Each of these has a ticket on the project board.

## Exported methods

- mount

`shallowMount` is not required for an alpha.

## mounting options

- [x] data
- [x] slots (support for scoped slots) #2
- [x] provide #27 
- [x] props
- [x] globals (contains mixins and plugins options) #28 

## VueWrapper

This is intentionally a minimal API. The primary way users will interact with their components is DOMWrapper in alpha.

- [x] find/findAll #7 
- [x] emitted
- [x] html
- [x] vm

## DOMWrapper

This is the bulk of the functionality.

- [x] classes
- [x] attributes
- [x] exists
- [x] element
- [x] text
- [x] html
- [x] find/findAll #7 
- [x] setValue (which is combined setChecked/setSelected etc) #29 
- [x] trigger

## Ecosystem

We will also need to release an alpha-0 for vue-jest. Branch here: https://github.com/vuejs/vue-jest/tree/next. If we don't provide this, people won't be able to test SFCs.

## Docs/Other

We should provide some examples on how to do things. We should also make sure it's possible to test things that were previously pain points, or new features:

- transitions
- suspense
- portals

## Nice to have

- provide example tests with vuex/vue-router?
